export const recipes = [

  // ============ MIC DEJUN ============

{
  id: 'breakfast_8',
  name: 'Ovăz cu Lapte și Banană',
  type: 'breakfast',
  fixed: false,
  budgetTier: 'budget',
  baseCost: 12,
  baseCalories: 480,
  baseMacros: { p: 18.5, c: 72.4, f: 10.2 },
  ingredients: [
    { key: 'oats', name: 'Fulgi de ovăz', amount: 80, unit: 'g' },
    { key: 'milk', name: 'Lapte', amount: 250, unit: 'ml' },
    { key: 'bananas', name: 'Banane', amount: 100, unit: 'g' },
  ],
  steps: [
    'Măsoară 80g de fulgi de ovăz și pune-i într-o oală mică. Adaugă 250ml lapte și pune pe foc mic-mediu.',
    'Amestecă continuu timp de 4-5 minute până când ovăzul absoarbe laptele și devine cremos. Dacă e prea gros, mai adaugă puțin lapte.',
    'Toarnă ovăzul în bol și lasă-l să se răcească 1-2 minute.',
    'Curăță banana și taie-o în felii subțiri, aranjează deasupra bolului.',
    'Condimente opționale: scorțișoară sau un strop de miere — nu influențează semnificativ caloriile și nu sunt obligatorii.',
  ],
},

{
  id: 'breakfast_10',
  name: 'Ouă Scramble cu Unt',
  type: 'breakfast',
  fixed: true,
  budgetTier: 'budget',
  baseCost: 18,
  baseCalories: 420,
  baseMacros: { p: 28.4, c: 2.2, f: 32.8 },
  ingredients: [
    { key: 'eggs', name: 'Ouă', amount: 4, unit: 'pcs' },
    { key: 'butter', name: 'Unt', amount: 15, unit: 'g' },
    { key: 'milk', name: 'Lapte', amount: 30, unit: 'ml' },
  ],
  steps: [
    'Sparge 4 ouă într-un bol, adaugă 30ml lapte, un praf de sare și piper. Bate bine cu o furculiță până devine omogen.',
    'Pune 15g unt într-o tigaie la foc mic. Lasă untul să se topească încet fără să se ardă.',
    'Toarnă ouăle bătute în tigaie și lasă-le 20-30 secunde fără să amesteci.',
    'Începe să amesteci ușor cu o spatulă de silicon, trăgând ouăle dinspre margini spre centru.',
    'Continuă să amesteci la foc mic timp de 2-3 minute până ouăle sunt cremoase și abia coagulate. Nu le lăsa să se întărească prea mult.',
    'Ia tigaia de pe foc cu 30 secunde înainte să fie gata — căldura reziduală termină gătirea. Servește imediat.',
  ],
},

  {
    id: 'breakfast_1',
    name: 'Ovăz cu Brânză de Vaci și Banană',
    type: 'breakfast',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 18,
    baseCalories: 541,
    baseMacros: { p: 37.9, c: 68.6, f: 11.9 },
    ingredients: [
      { key: 'oats', name: 'Fulgi de ovăz', amount: 80, unit: 'g' },
      { key: 'cottage cheese', name: 'Brânză de vaci', amount: 150, unit: 'g' },
      { key: 'bananas', name: 'Banane', amount: 100, unit: 'g' },
    ],
    steps: [
      'Măsoară 80g de fulgi de ovăz și pune-i într-o oală mică. Adaugă 200ml apă rece și pune pe foc mediu.',
      'Amestecă continuu timp de 4-5 minute până când ovăzul absoarbe apa și devine cremos. Dacă e prea gros, mai adaugă puțină apă.',
      'Toarnă ovăzul în bol și lasă-l să se răcească 1-2 minute.',
      'Adaugă 150g brânză de vaci deasupra și amestecă ușor sau las-o ca topping.',
      'Curăță banana și taie-o în felii subțiri, aranjează deasupra bolului.',
      'Condimente opționale: scorțișoară sau un strop de miere — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'breakfast_2',
    name: 'Ouă Jumări cu Pâine',
    type: 'breakfast',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 22,
    baseCalories: 634,
    baseMacros: { p: 25.3, c: 54.8, f: 29.7 },
    ingredients: [
      { key: 'eggs', name: 'Ouă', amount: 3, unit: 'pcs' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 5, unit: 'ml' },
      { key: 'bread', name: 'Pâine albă', amount: 100, unit: 'g' },
    ],
    steps: [
      'Pune o tigaie pe foc mediu și adaugă 5ml ulei de floarea soarelui. Lasă uleiul să se încălzească 1 minut.',
      'Sparge cele 3 ouă într-un bol, adaugă un praf de sare și bate-le bine cu o furculiță până devin omogene.',
      'Toarnă ouăle bătute în tigaie și începe să amesteci ușor cu o spatulă de silicon sau lemn.',
      'Gătește pe foc mediu-mic timp de 2-3 minute, amestecând continuu pentru ouă cremoase. Nu le lăsa să se usuce.',
      'Pune ouăle pe farfurie alături de 100g pâine albă.',
      'Condimente opționale: sare, piper, ceapă verde tocată sau roșii feliate — nu influențează caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'breakfast_3',
    name: 'Iaurt Grecesc cu Ovăz și Banană',
    type: 'breakfast',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 28,
    baseCalories: 394,
    baseMacros: { p: 21.8, c: 66.1, f: 4.6 },
    ingredients: [
      { key: 'greek yogurt', name: 'Iaurt grecesc 0%', amount: 150, unit: 'g' },
      { key: 'oats', name: 'Fulgi de ovăz', amount: 60, unit: 'g' },
      { key: 'bananas', name: 'Banane', amount: 120, unit: 'g' },
    ],
    steps: [
      'Măsoară 150g iaurt grecesc și pune-l într-un bol adânc.',
      'Adaugă 60g fulgi de ovăz uscați peste iaurt și amestecă bine până se combină uniform.',
      'Lasă amestecul să stea 5-10 minute — ovăzul va absorbi puțin din iaurt și va deveni mai moale și mai ușor de mâncat.',
      'Curăță banana și taie-o în felii rotunde, adaugă deasupra bolului.',
      'Servește imediat sau păstrează la frigider până la 30 de minute pentru o textură mai densă.',
      'Condimente opționale: scorțișoară sau câteva picături de miere — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'breakfast_4',
    name: 'Omletă cu Legume și Pâine',
    type: 'breakfast',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 25,
    baseCalories: 628,
    baseMacros: { p: 24.8, c: 47.6, f: 32.9 },
    ingredients: [
      { key: 'eggs', name: 'Ouă', amount: 3, unit: 'pcs' },
      { key: 'bell peppers', name: 'Ardei gras roșu', amount: 80, unit: 'g' },
      { key: 'tomatoes', name: 'Roșii', amount: 100, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 8, unit: 'ml' },
      { key: 'bread', name: 'Pâine albă', amount: 70, unit: 'g' },
    ],
    steps: [
      'Taie 80g ardei gras în fâșii subțiri și 100g roșii în cuburi mici.',
      'Încălzește 5ml ulei într-o tigaie la foc mediu. Adaugă ardeiul și gătește 3-4 minute până se înmoaie ușor. Adaugă roșiile și mai gătește 2 minute. Pune legumele deoparte.',
      'Bate cele 3 ouă cu un praf de sare într-un bol până devin spumoase.',
      'Adaugă restul de 3ml ulei în tigaie la foc mediu-mic. Toarnă ouăle bătute și lasă-le să se întărească la margini fără să amesteci, aproximativ 2 minute.',
      'Pune legumele pe jumătate din omletă, pliază cealaltă jumătate peste ele și lasă 1 minut pe foc.',
      'Servește alături de 70g pâine.',
      'Condimente opționale: sare, piper, boia dulce, ierburi proaspete — nu influențează caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'breakfast_5',
    name: 'Brânză de Vaci cu Ovăz și Mere',
    type: 'breakfast',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 20,
    baseCalories: 490,
    baseMacros: { p: 37.5, c: 54.1, f: 14.8 },
    ingredients: [
      { key: 'cottage cheese', name: 'Brânză de vaci 5.5%', amount: 200, unit: 'g' },
      { key: 'oats', name: 'Fulgi de ovăz', amount: 50, unit: 'g' },
      { key: 'apples', name: 'Mere roșii', amount: 150, unit: 'g' },
    ],
    steps: [
      'Măsoară 200g brânză de vaci și pune-o într-un bol adânc.',
      'Adaugă 50g fulgi de ovăz uscați și amestecă bine cu o furculiță până se combină uniform.',
      'Lasă amestecul să stea 5-7 minute — ovăzul va absorbi umiditatea din brânză și va deveni mai moale.',
      'Spală și taie 150g mere în cuburi mici sau felii subțiri, cu sau fără coajă după preferință.',
      'Adaugă merele deasupra sau amestecă-le înăuntru.',
      'Servește imediat sau păstrează la frigider până la 20 de minute.',
      'Condimente opționale: scorțișoară, un strop de miere — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'breakfast_6',
    name: 'Ouă Fierte cu Pâine și Roșii',
    type: 'breakfast',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 18,
    baseCalories: 617,
    baseMacros: { p: 26.7, c: 60.7, f: 25 },
    ingredients: [
      { key: 'eggs', name: 'Ouă', amount: 3, unit: 'pcs' },
      { key: 'bread', name: 'Pâine albă', amount: 100, unit: 'g' },
      { key: 'tomatoes', name: 'Roșii', amount: 150, unit: 'g' },
    ],
    steps: [
      'Pune un litru de apă la fiert într-o oală. Când fierbe, adaugă ușor cele 3 ouă cu o lingură pentru a nu le crăpa.',
      'Pentru ouă tari: fierbe exact 10 minute. Pentru ouă moi cu gălbenușul cremos: fierbe 6-7 minute.',
      'Scoate ouăle și pune-le imediat în apă rece pentru 3-4 minute — oprește gătirea și face coaja mai ușor de desprins.',
      'Curăță ouăle de coajă și taie-le în jumătăți sau felii.',
      'Taie 150g roșii în felii rotunde și aranjează pe farfurie alături de ouă și 100g pâine.',
      'Condimente opționale: sare, piper, ulei de măsline stropit pe roșii — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'breakfast_7',
    name: 'Chefir cu Ovăz și Banană',
    type: 'breakfast',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 16,
    baseCalories: 443,
    baseMacros: { p: 18.5, c: 70.9, f: 7.7 },
    ingredients: [
      { key: 'kefir', name: 'Chefir 1%', amount: 250, unit: 'g' },
      { key: 'oats', name: 'Fulgi de ovăz', amount: 70, unit: 'g' },
      { key: 'bananas', name: 'Banane', amount: 100, unit: 'g' },
    ],
    steps: [
      'Măsoară 250g chefir și toarnă-l într-un bol sau pahar mare.',
      'Adaugă 70g fulgi de ovăz și amestecă bine.',
      'Lasă amestecul la frigider 10-15 minute sau peste noapte pentru o textură mai groasă și mai cremoasă.',
      'Curăță banana și taie-o în felii subțiri, adaugă deasupra înainte de servire.',
      'Dacă e prea gros după răcire, mai adaugă puțin chefir și amestecă.',
      'Condimente opționale: scorțișoară, vanilie — nu influențează caloriile și nu sunt obligatorii.',
    ],
  },

  {
  id: 'breakfast_9',
  name: 'Omletă cu Mozzarella și Roșii',
  type: 'breakfast',
  fixed: false,
  budgetTier: 'medium',
  baseCost: 32,
  baseCalories: 520,
  baseMacros: { p: 35.2, c: 4.8, f: 38.6 },
  ingredients: [
    { key: 'eggs', name: 'Ouă', amount: 3, unit: 'pcs' },
    { key: 'mozzarella', name: 'Mozzarella', amount: 80, unit: 'g' },
    { key: 'tomatoes', name: 'Roșii', amount: 100, unit: 'g' },
    { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 10, unit: 'ml' },
  ],
  steps: [
    'Sparge 3 ouă într-un bol, adaugă un praf de sare și piper și bate bine cu o furculiță.',
    'Taie 100g roșii în cuburi mici și 80g mozzarella în felii subțiri.',
    'Încălzește 10ml ulei într-o tigaie la foc mediu.',
    'Toarnă ouăle bătute în tigaie și lasă să se întărească ușor pe margini, aproximativ 2 minute.',
    'Adaugă roșiile și mozzarella pe jumătate din omletă.',
    'Pliază omleta în jumătate peste umplutură și mai lasă 1-2 minute până mozzarella se topește. Servește imediat.',
  ],
},

{
  id: 'breakfast_11',
  name: 'Shake Proteic cu Banană',
  type: 'breakfast',
  fixed: true,
  budgetTier: 'budget',
  baseCost: 25,
  baseCalories: 320,
  baseMacros: { p: 43, c: 28, f: 5 },
  ingredients: [
    { key: 'protein powder', name: 'Proteină din zer', amount: 2, unit: 'scoops' },
    { key: 'milk', name: 'Lapte', amount: 300, unit: 'ml' },
    { key: 'bananas', name: 'Banane', amount: 100, unit: 'g' },
  ],
  steps: [
    'Pune 300ml lapte rece în blender.',
    'Adaugă 2 linguri de proteină din zer și banana tăiată în bucăți.',
    'Mixează 30-60 secunde până obții o textură omogenă.',
    'Servește imediat.',
  ],
},

{
  id: 'breakfast_12',
  name: 'Toast cu Avocado și Ouă Poșate',
  type: 'breakfast',
  fixed: false,
  budgetTier: 'medium',
  baseCost: 38,
  baseCalories: 520,
  baseMacros: { p: 24.6, c: 34.2, f: 28.4 },
  ingredients: [
    { key: 'bread', name: 'Pâine', amount: 100, unit: 'g' },
    { key: 'avocado', name: 'Avocado', amount: 120, unit: 'g' },
    { key: 'eggs', name: 'Ouă', amount: 2, unit: 'pcs' },
    { key: 'lemon', name: 'Lămâie', amount: 20, unit: 'g' },
    { key: 'tomatoes', name: 'Roșii', amount: 80, unit: 'g' },
  ],
  steps: [
    'Umple o oală adâncă cu apă și adaugă un strop de oțet. Aduce la fierbere ușoară.',
    'Sparge fiecare ou într-o cană mică. Amestecă apa în formă circulară și alunecă oul în centru. Fierbe 3 minute pentru gălbenuș moale.',
    'Zdrobește 120g avocado cu o furculiță, adaugă zeamă de lămâie, sare și piper după gust.',
    'Prăjește 100g pâine în toaster sau tigaie uscată până devine crocantă.',
    'Întinde avocado pe pâine, adaugă felii de roșii și ouăle poșate deasupra.',
    'Condimentează cu sare, piper și fulgi de ardei iute opțional. Servește imediat.',
  ],
},

{
  id: 'breakfast_13',
  name: 'Budincă de Ovăz cu Proteină și Afine',
  type: 'breakfast',
  fixed: false,
  budgetTier: 'medium',
  baseCost: 42,
  baseCalories: 490,
  baseMacros: { p: 38.2, c: 58.4, f: 8.6 },
  ingredients: [
    { key: 'oats', name: 'Fulgi de ovăz', amount: 80, unit: 'g' },
    { key: 'protein powder', name: 'Proteină din zer', amount: 1, unit: 'scoops' },
    { key: 'milk', name: 'Lapte', amount: 200, unit: 'ml' },
    { key: 'blueberries', name: 'Afine', amount: 80, unit: 'g' },
    { key: 'honey', name: 'Miere', amount: 15, unit: 'g' },
  ],
  steps: [
    'Pune 80g fulgi de ovăz într-un borcan sau bol cu capac.',
    'Amestecă 1 scoop de proteină cu 200ml lapte rece până se dizolvă complet.',
    'Toarnă laptele cu proteină peste fulgi și amestecă bine.',
    'Adaugă 15g miere și amestecă din nou.',
    'Acoperă și pune la frigider minim 4 ore sau peste noapte.',
    'Dimineața adaugă 80g afine proaspete deasupra și servește rece.',
  ],
},

{
  id: 'breakfast_14',
  name: 'Omletă cu Somon și Cremă de Brânză',
  type: 'breakfast',
  fixed: false,
  budgetTier: 'medium',
  baseCost: 65,
  baseCalories: 480,
  baseMacros: { p: 38.6, c: 3.2, f: 34.8 },
  ingredients: [
    { key: 'eggs', name: 'Ouă', amount: 3, unit: 'pcs' },
    { key: 'smoked salmon', name: 'Somon felii sărat', amount: 80, unit: 'g' },
    { key: 'cream cheese', name: 'Cremă de brânză', amount: 40, unit: 'g' },
    { key: 'dill', name: 'Mărar', amount: 10, unit: 'g' },
    { key: 'butter', name: 'Unt', amount: 10, unit: 'g' },
  ],
  steps: [
    'Sparge 3 ouă într-un bol, adaugă sare și piper și bate cu o furculiță.',
    'Toacă mărunt 10g mărar proaspăt.',
    'Topește 10g unt într-o tigaie la foc mediu.',
    'Toarnă ouăle și lasă să se coaguleze ușor pe margini, aproximativ 2 minute.',
    'Adaugă 40g cremă de brânză în puncte pe jumătate din omletă, apoi 80g somon tăiat în bucăți mici și mărarul tocat.',
    'Pliază omleta în jumătate și mai lasă 1 minut pe foc. Servește imediat.',
  ],
},

  // ============ PRÂNZ ============

  {
    id: 'lunch_1',
    name: 'Piept de Pui cu Orez și Morcovi',
    type: 'lunch',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 35,
    baseCalories: 692,
    baseMacros: { p: 62.3, c: 67.4, f: 17.5 },
    ingredients: [
      { key: 'chicken breast', name: 'Piept de pui', amount: 180, unit: 'g' },
      { key: 'rice', name: 'Orez clasic', amount: 80, unit: 'g' },
      { key: 'carrots', name: 'Morcovi', amount: 100, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 10, unit: 'ml' },
    ],
    steps: [
      'Spală 80g orez sub apă rece până apa devine limpede. Pune-l într-o oală cu 200ml apă și un praf de sare, aduce la fierbere.',
      'Reduce focul la mic, acoperă oala și lasă să fiarbă 15-18 minute până apa e absorbită complet. Nu ridica capacul în timpul fierberii.',
      'Între timp, curăță și taie 100g morcovi în rondele sau bețișoare. Fierbe-i în apă cu sare 8-10 minute până sunt moi dar nu desfăcuți.',
      'Bate ușor pieptul de pui cu un ciocan de bucătărie pentru grosime uniformă. Condimentează cu sare și piper pe ambele părți.',
      'Încălzește 10ml ulei într-o tigaie la foc mediu-mare. Adaugă pieptul și gătește 6-7 minute pe fiecare parte până e auriu la exterior și alb complet la interior.',
      'Lasă pieptul să se odihnească 2-3 minute înainte de a-l tăia, pentru a păstra sucurile.',
      'Condimente opționale: usturoi, boia de ardei, cimbru — nu influențează caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'lunch_2',
    name: 'Ton cu Hrișcă și Roșii',
    type: 'lunch',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 32,
    baseCalories: 479,
    baseMacros: { p: 44, c: 60.3, f: 8.5 },
    ingredients: [
      { key: 'tuna', name: 'Ton în apă', amount: 112, unit: 'g' },
      { key: 'buckwheat', name: 'Hrișcă', amount: 80, unit: 'g' },
      { key: 'tomatoes', name: 'Roșii', amount: 150, unit: 'g' },
      { key: 'olive oil', name: 'Ulei de măsline', amount: 5, unit: 'ml' },
    ],
    steps: [
      'Clătește 80g hrișcă sub apă rece. Pune-o într-o oală cu 200ml apă și un praf de sare la foc mare.',
      'Când începe să fiarbă, reduce focul la mic și acoperă. Gătește 13-15 minute până apa e absorbită și hrișca e moale.',
      'Scurge tonul din conservă și pune-l într-un bol. Separă bucățile ușor cu o furculiță.',
      'Taie 150g roșii în cuburi sau felii și adaugă peste ton.',
      'Adaugă hrișca fiartă în bol, toarnă 5ml ulei de măsline deasupra și amestecă ușor.',
      'Servește cald sau la temperatura camerei.',
      'Condimente opționale: sare, piper, zeamă de lămâie, ceapă roșie — nu influențează caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'lunch_3',
    name: 'Paste Bolognese cu Carne Tocată',
    type: 'lunch',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 45,
    baseCalories: 666,
    baseMacros: { p: 46.9, c: 82.1, f: 16.2 },
    ingredients: [
      { key: 'minced meat', name: 'Carne tocată mix', amount: 150, unit: 'g' },
      { key: 'pasta', name: 'Spaghetti', amount: 100, unit: 'g' },
      { key: 'pasta sauce', name: 'Sos paste Arrabbiata', amount: 150, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 10, unit: 'ml' },
    ],
    steps: [
      'Fierbe apă în oală mare cu sare. Adaugă 100g spaghetti și gătește conform instrucțiunilor de pe pachet, de obicei 8-10 minute pentru al dente.',
      'Între timp, încălzește 10ml ulei într-o tigaie adâncă la foc mediu-mare.',
      'Adaugă 150g carne tocată și gătește 6-8 minute, amestecând și sfărâmând bucățile cu o spatulă până nu mai e roz deloc.',
      'Reduce focul la mediu, adaugă 150g sos Arrabbiata și amestecă bine. Lasă să fiarbă la foc mic 3-4 minute.',
      'Scurge pastele și adaugă-le direct în tigaia cu sos, amestecă 1 minut pe foc pentru a combina.',
      'Servește imediat cât e cald.',
      'Condimente opționale: usturoi, oregano, fulgi de chili, parmezan — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'lunch_4',
    name: 'Piept de Pui cu Paste și Sos Arrabbiata',
    type: 'lunch',
    fixed: false,
    budgetTier: 'mid',
    baseCost: 55,
    baseCalories: 759,
    baseMacros: { p: 61.9, c: 82.1, f: 18.3 },
    ingredients: [
      { key: 'chicken breast', name: 'Piept de pui', amount: 150, unit: 'g' },
      { key: 'pasta', name: 'Spaghetti', amount: 100, unit: 'g' },
      { key: 'pasta sauce', name: 'Sos paste Arrabbiata', amount: 150, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 10, unit: 'ml' },
    ],
    steps: [
      'Fierbe apă cu sare într-o oală mare. Adaugă 100g spaghetti și gătește 8-10 minute până sunt al dente. Scurge și păstrează 50ml din apa de la paste.',
      'Taie 150g piept de pui în fâșii subțiri de aproximativ 1cm grosime.',
      'Încălzește 10ml ulei într-o tigaie mare la foc mediu-mare. Adaugă puiul și gătește 5-6 minute, amestecând ocazional, până e auriu și gătit complet.',
      'Reduce focul la mediu, adaugă 150g sos Arrabbiata și amestecă cu puiul. Lasă să fiarbă 2-3 minute.',
      'Adaugă pastele scurse direct în tigaie și amestecă bine. Dacă sosul e prea gros, adaugă puțin din apa de la paste.',
      'Servește imediat cât e fierbinte.',
      'Condimente opționale: usturoi, oregano, fulgi de chili, piper — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'lunch_5',
    name: 'Linte cu Morcovi și Ceapă',
    type: 'lunch',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 22,
    baseCalories: 500,
    baseMacros: { p: 27.5, c: 70.8, f: 11.9 },
    ingredients: [
      { key: 'lentils', name: 'Linte roșie', amount: 100, unit: 'g' },
      { key: 'carrots', name: 'Morcovi', amount: 150, unit: 'g' },
      { key: 'onions', name: 'Ceapă galbenă', amount: 100, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 10, unit: 'ml' },
    ],
    steps: [
      'Clătește 100g linte roșie sub apă rece. Pune-o într-o oală cu 400ml apă și aduce la fierbere.',
      'Reduce focul și lasă să fiarbă 15-20 minute până lintea e moale și cremoasă. Amestecă ocazional și adaugă apă dacă e necesar.',
      'Între timp, curăță și taie 150g morcovi în rondele și 100g ceapă în cuburi mici.',
      'Încălzește 10ml ulei într-o tigaie la foc mediu. Adaugă ceapa și gătește 4-5 minute până devine translucidă și ușor aurie.',
      'Adaugă morcovii și mai gătește 5-6 minute amestecând ocazional.',
      'Combină legumele călite cu lintea fiartă, amestecă bine și lasă 2 minute pe foc împreună.',
      'Condimente opționale: chimen, turmeric, usturoi, boia de ardei — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'lunch_6',
    name: 'Fasole cu Carne Tocată',
    type: 'lunch',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 38,
    baseCalories: 653,
    baseMacros: { p: 48, c: 77.3, f: 16.4 },
    ingredients: [
      { key: 'minced meat', name: 'Carne tocată mix', amount: 150, unit: 'g' },
      { key: 'canned beans', name: 'Fasole albă în sos de tomat', amount: 205, unit: 'g' },
      { key: 'onions', name: 'Ceapă galbenă', amount: 80, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 10, unit: 'ml' },
      { key: 'bread', name: 'Pâine albă', amount: 70, unit: 'g' },
    ],
    steps: [
      'Curăță și taie 80g ceapă în cuburi mici.',
      'Încălzește 10ml ulei într-o oală la foc mediu. Adaugă ceapa și gătește 4-5 minute până devine aurie.',
      'Adaugă 150g carne tocată și gătește 6-8 minute, amestecând și sfărâmând bucățile, până nu mai e roz deloc.',
      'Adaugă conserva de fasole albă în sos de tomat și amestecă bine cu carnea.',
      'Reduce focul la mic și lasă să fiarbă împreună 10-12 minute până sosul se îngroașă ușor.',
      'Servește cald alături de 70g pâine pentru a înmuia în sos.',
      'Condimente opționale: usturoi, cimbru, boia de ardei, frunze de dafin — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'lunch_7',
    name: 'Năut cu Legume și Orez',
    type: 'lunch',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 28,
    baseCalories: 726,
    baseMacros: { p: 25.1, c: 111, f: 17.1 },
    ingredients: [
      { key: 'chickpeas', name: 'Năut', amount: 100, unit: 'g' },
      { key: 'rice', name: 'Orez clasic', amount: 60, unit: 'g' },
      { key: 'bell peppers', name: 'Ardei gras roșu', amount: 100, unit: 'g' },
      { key: 'tomatoes', name: 'Roșii', amount: 100, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 10, unit: 'ml' },
    ],
    steps: [
      'Clătește 100g năut uscat și pune-l la fiert în 500ml apă cu sare la foc mare. Când fierbe, reduce la mediu și lasă 40-45 minute până e moale. Alternativ folosește năut din conservă și sari la pasul 3.',
      'Spală 60g orez și fierbe-l în 150ml apă cu sare la foc mic, acoperit, 15-18 minute.',
      'Taie 100g ardei gras în cuburi și 100g roșii în cuburi mici.',
      'Încălzește 10ml ulei într-o tigaie la foc mediu. Adaugă ardeiul și gătește 4 minute, apoi adaugă roșiile și mai gătește 3 minute.',
      'Adaugă năutul fiert și orezul în tigaie, amestecă bine și gătește împreună 2-3 minute.',
      'Condimente opționale: chimen, turmeric, coriandru, usturoi — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },
  
  {
  id: 'lunch_8',
  name: 'Salată Grecească cu Feta',
  type: 'lunch',
  fixed: false,
  budgetTier: 'budget',
  baseCost: 28,
  baseCalories: 380,
  baseMacros: { p: 12.5, c: 14.2, f: 28.6 },
  ingredients: [
    { key: 'tomatoes', name: 'Roșii', amount: 200, unit: 'g' },
    { key: 'cucumbers', name: 'Castraveți', amount: 150, unit: 'g' },
    { key: 'bell peppers', name: 'Ardei gras', amount: 100, unit: 'g' },
    { key: 'onions', name: 'Ceapă roșie', amount: 50, unit: 'g' },
    { key: 'feta', name: 'Brânză feta', amount: 80, unit: 'g' },
    { key: 'olive oil', name: 'Ulei de măsline', amount: 15, unit: 'ml' },
  ],
  steps: [
    'Taie 200g roșii în cuburi mari și pune-le într-un bol.',
    'Taie 150g castraveți în rondele sau jumătăți și adaugă peste roșii.',
    'Taie 100g ardei gras în fâșii și 50g ceapă roșie în inele subțiri, adaugă în bol.',
    'Taie 80g brânză feta în cuburi și adaugă deasupra legumelor.',
    'Toarnă 15ml ulei de măsline și condimentează cu sare, piper și oregano după gust.',
    'Amestecă ușor și servește imediat.',
  ],
},


{
  id: 'lunch_9',
  name: 'Paste cu Pui și Parmezan',
  type: 'lunch',
  fixed: false,
  budgetTier: 'medium',
  baseCost: 38,
  baseCalories: 680,
  baseMacros: { p: 52.4, c: 72.6, f: 16.8 },
  ingredients: [
    { key: 'pasta', name: 'Paste făinoase', amount: 150, unit: 'g' },
    { key: 'chicken breast', name: 'Piept de pui', amount: 180, unit: 'g' },
    { key: 'parmesan', name: 'Parmezan', amount: 20, unit: 'g' },
    { key: 'tomatoes', name: 'Roșii', amount: 150, unit: 'g' },
    { key: 'garlic', name: 'Usturoi', amount: 10, unit: 'g' },
    { key: 'olive oil', name: 'Ulei de măsline', amount: 15, unit: 'ml' },
  ],
  steps: [
    'Taie 180g piept de pui în cuburi mici și condimentează cu sare, piper și oregano.',
    'Încălzește 15ml ulei de măsline într-o tigaie la foc mediu. Adaugă 10g usturoi tocat și călește 1 minut.',
    'Adaugă cuburile de pui și gătește 6-8 minute până sunt gătite complet pe toate părțile.',
    'Adaugă 150g roșii tăiate în cuburi și gătește încă 3-4 minute până se înmoaie.',
    'În același timp fierbe 150g paste în apă cu sare conform instrucțiunilor, aproximativ 8-10 minute.',
    'Scurge pastele și adaugă-le în tigaie peste pui și roșii. Amestecă bine.',
    'Servește cu 20g parmezan ras deasupra și piper negru după gust.',
  ],
},


{
  id: 'lunch_10',
  name: 'Paste Alfredo cu Pui',
  type: 'lunch',
  fixed: false,
  budgetTier: 'medium',
  baseCost: 52,
  baseCalories: 720,
  baseMacros: { p: 48.2, c: 68.4, f: 24.6 },
  ingredients: [
    { key: 'pasta', name: 'Paste făinoase', amount: 150, unit: 'g' },
    { key: 'chicken breast', name: 'Piept de pui', amount: 180, unit: 'g' },
    { key: 'heavy cream', name: 'Frișcă', amount: 80, unit: 'ml' },
    { key: 'parmesan', name: 'Parmezan', amount: 20, unit: 'g' },
    { key: 'garlic', name: 'Usturoi', amount: 10, unit: 'g' },
    { key: 'butter', name: 'Unt', amount: 15, unit: 'g' },
  ],
  steps: [
    'Fierbe 150g paste în apă cu sare conform instrucțiunilor, aproximativ 8-10 minute. Păstrează 50ml din apa de la paste înainte de a le scurge.',
    'Taie 180g piept de pui în fâșii subțiri și condimentează cu sare și piper.',
    'Topește 15g unt într-o tigaie la foc mediu. Adaugă puiul și gătește 5-6 minute până este auriu și gătit complet.',
    'Adaugă 10g usturoi tocat și gătește 1 minut.',
    'Toarnă 80ml frișcă în tigaie și lasă să fiarbă ușor 2-3 minute până se îngroașă puțin.',
    'Adaugă pastele scurse și 20g parmezan ras. Amestecă bine, adaugă puțin din apa de paste dacă sosul e prea gros. Servește imediat.',
  ],
},

{
  id: 'lunch_11',
  name: 'Zeamă de Pui',
  type: 'lunch',
  fixed: false,
  budgetTier: 'budget',
  baseCost: 28,
  baseCalories: 420,
  baseMacros: { p: 38.4, c: 28.6, f: 12.2 },
  ingredients: [
    { key: 'chicken breast', name: 'Piept de pui', amount: 200, unit: 'g' },
    { key: 'potatoes', name: 'Cartofi', amount: 150, unit: 'g' },
    { key: 'carrots', name: 'Morcovi', amount: 80, unit: 'g' },
    { key: 'onions', name: 'Ceapă', amount: 60, unit: 'g' },
    { key: 'bors', name: 'Borș acru', amount: 200, unit: 'ml' },
    { key: 'leustean', name: 'Leuștean', amount: 2, unit: 'g' },
  ],
  steps: [
    'Pune 200g piept de pui întreg într-o oală cu 1.5l apă rece. Adaugă 60g ceapă curățată întreagă și 80g morcovi tăiați în rondele. Fierbe la foc mediu 25-30 minute, îndepărtând spuma.',
    'Scoate pieptul de pui, lasă-l să se răcească puțin și rupe-l în bucăți cu mâna sau taie-l în cuburi.',
    'Adaugă 150g cartofi tăiați în cuburi în zeama rămasă și fierbe încă 15 minute până sunt moi.',
    'Toarnă 200ml borș acru în oală și lasă să fiarbă 5 minute. Gustă și adaugă mai mult borș dacă vrei mai acru.',
    'Adaugă bucățile de pui înapoi în oală.',
    'Adaugă un praf de leuștean uscat (foarte puțin — e puternic!), sare și piper după gust. Servește fierbinte.',
  ],
},

  // ============ CINĂ ============

  {
    id: 'dinner_1',
    name: 'File de Pește cu Cartofi și Broccoli',
    type: 'dinner',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 38,
    baseCalories: 475,
    baseMacros: { p: 43.6, c: 44.5, f: 15.2 },
    ingredients: [
      { key: 'fish fillet', name: 'File de merluciu', amount: 200, unit: 'g' },
      { key: 'potatoes', name: 'Cartofi albi', amount: 200, unit: 'g' },
      { key: 'broccoli', name: 'Broccoli', amount: 150, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 10, unit: 'ml' },
    ],
    steps: [
      'Deconghelează fileul de pește în prealabil în frigider sau sub apă rece curentă timp de 10-15 minute. Usucă-l bine cu un prosop de hârtie.',
      'Curăță și taie 200g cartofi în cuburi sau sferturi. Pune-i la fiert în apă sărată pentru 15-20 minute până sunt moi la furculiță.',
      'Împarte 150g broccoli în buchețele și adaugă-l în aceeași oală cu cartofii în ultimele 5-7 minute de fierbere.',
      'Condimentează fileul de pește cu sare și piper pe ambele fețe.',
      'Încălzește 10ml ulei într-o tigaie la foc mediu-mare. Gătește peștele 3-4 minute pe fiecare parte până e auriu la exterior și se desface ușor la presiunea furculiței.',
      'Aranjează pe farfurie peștele alături de cartofi și broccoli.',
      'Condimente opționale: zeamă de lămâie, usturoi, boia dulce sau ierburi aromatice — nu influențează caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'dinner_2',
    name: 'Pulpe de Pui cu Hrișcă și Varză',
    type: 'dinner',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 40,
    baseCalories: 819,
    baseMacros: { p: 62.1, c: 63.4, f: 38.3 },
    ingredients: [
      { key: 'chicken thighs', name: 'Gambe de pui', amount: 200, unit: 'g' },
      { key: 'buckwheat', name: 'Hrișcă', amount: 80, unit: 'g' },
      { key: 'cabbage', name: 'Varză albă', amount: 150, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 10, unit: 'ml' },
    ],
    steps: [
      'Clătește 80g hrișcă sub apă rece și pune-o la fiert în 200ml apă cu sare la foc mediu. Când fierbe, reduce la mic și acoperă 13-15 minute.',
      'Condimentează pulpele de pui cu sare și piper pe toate părțile.',
      'Încălzește 10ml ulei într-o tigaie mare la foc mediu. Adaugă pulpele cu pielea în jos și gătește 8-10 minute fără să le miști, până pielea e crocantă și aurie.',
      'Întoarce pulpele și gătește încă 8-10 minute pe cealaltă parte până sunt gătite complet. Verifică prin tăiere — sucul trebuie să fie limpede, nu roz.',
      'Scoate pulpele din tigaie. În aceeași tigaie cu grăsimea rămasă, adaugă 150g varză tăiată fâșii subțiri. Gătește 5-7 minute la foc mediu până se înmoaie ușor.',
      'Aranjează pe farfurie hrișca, varza și pulpele de pui.',
      'Condimente opționale: chimen, usturoi, boia de ardei sau muștar — nu influențează caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'dinner_3',
    name: 'Ton cu Cartofi și Mazăre',
    type: 'dinner',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 35,
    baseCalories: 506,
    baseMacros: { p: 47.9, c: 54.5, f: 9.4 },
    ingredients: [
      { key: 'tuna', name: 'Ton în apă', amount: 112, unit: 'g' },
      { key: 'potatoes', name: 'Cartofi albi', amount: 250, unit: 'g' },
      { key: 'canned peas', name: 'Mazăre verde conservată', amount: 150, unit: 'g' },
      { key: 'olive oil', name: 'Ulei de măsline', amount: 5, unit: 'ml' },
    ],
    steps: [
      'Curăță și taie 250g cartofi în cuburi egale de aproximativ 2cm. Pune-i la fiert în apă sărată pentru 15-18 minute până sunt moi la furculiță.',
      'În ultimele 5 minute de fierbere a cartofilor, adaugă 150g mazăre conservată scursă în aceeași oală pentru a o încălzi.',
      'Scurge totul și lasă să se răcească 2-3 minute.',
      'Scurge tonul din conservă și pune-l într-un bol mare. Separă bucățile cu o furculiță.',
      'Adaugă cartofii și mazărea peste ton, toarnă 5ml ulei de măsline și amestecă ușor pentru a nu zdrobi cartofii.',
      'Servește cald sau la temperatura camerei.',
      'Condimente opționale: sare, piper, zeamă de lămâie, ceapă roșie tocată — nu influențează caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'dinner_4',
    name: 'Piept de Pui cu Broccoli și Orez',
    type: 'dinner',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 38,
    baseCalories: 686,
    baseMacros: { p: 66.3, c: 64.3, f: 18 },
    ingredients: [
      { key: 'chicken breast', name: 'Piept de pui', amount: 180, unit: 'g' },
      { key: 'rice', name: 'Orez clasic', amount: 70, unit: 'g' },
      { key: 'broccoli', name: 'Broccoli', amount: 200, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 10, unit: 'ml' },
    ],
    steps: [
      'Spală 70g orez și pune-l la fiert în 175ml apă cu sare la foc mic, acoperit, 15-18 minute.',
      'Împarte 200g broccoli în buchețele mici și uniforme. Fierbe-le în apă sărată 5-6 minute până sunt fragede dar încă verzi și crocante.',
      'Bate ușor pieptul de pui cu un ciocan sau fundul unei tigăi pentru grosime uniformă. Condimentează cu sare și piper.',
      'Încălzește 10ml ulei într-o tigaie la foc mediu-mare. Gătește pieptul 6-7 minute pe fiecare parte până e auriu la exterior și complet alb la interior.',
      'Lasă pieptul să se odihnească 3 minute pe un fund de lemn, apoi taie-l în felii diagonale.',
      'Aranjează pe farfurie orezul, broccoli și pieptul feliat.',
      'Condimente opționale: usturoi, ghimbir, sos de soia, lămâie — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'dinner_5',
    name: 'Carne Tocată cu Cartofi și Varză',
    type: 'dinner',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 42,
    baseCalories: 652,
    baseMacros: { p: 51.5, c: 70.4, f: 20 },
    ingredients: [
      { key: 'minced meat', name: 'Carne tocată mix', amount: 200, unit: 'g' },
      { key: 'potatoes', name: 'Cartofi albi', amount: 300, unit: 'g' },
      { key: 'cabbage', name: 'Varză albă', amount: 200, unit: 'g' },
      { key: 'onions', name: 'Ceapă galbenă', amount: 80, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 15, unit: 'ml' },
    ],
    steps: [
      'Curăță și taie 300g cartofi în cuburi. Fierbe-i în apă sărată 15-18 minute până sunt moi. Scurge și zdrobește-i ușor cu o furculiță — nu trebuie să fie piure fin, ci rustic.',
      'Taie 200g varză în fâșii subțiri și 80g ceapă în cuburi mici.',
      'Încălzește 10ml ulei într-o tigaie mare la foc mediu. Adaugă ceapa și gătește 4 minute. Adaugă varza și gătește 7-8 minute amestecând, până se înmoaie și capătă ușor culoare aurie.',
      'Într-o altă tigaie, încălzește 5ml ulei la foc mare. Adaugă carnea tocată și gătește 6-8 minute sfărâmând bine, până e complet gătită și ușor rumenită.',
      'Combină carnea cu varza și ceapa în tigaia mare, amestecă bine și gătește împreună 2-3 minute.',
      'Servește alături de cartofii zdrobiți.',
      'Condimente opționale: usturoi, cimbru, boia de ardei, piper — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'dinner_6',
    name: 'File de Pește cu Couscous și Legume Congelate',
    type: 'dinner',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 40,
    baseCalories: 638,
    baseMacros: { p: 49.6, c: 68.1, f: 16.95 },
    ingredients: [
      { key: 'fish fillet', name: 'File de merluciu', amount: 200, unit: 'g' },
      { key: 'couscous', name: 'Couscous', amount: 80, unit: 'g' },
      { key: 'frozen vegetables mix', name: 'Legume congelate mix', amount: 150, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 10, unit: 'ml' },
    ],
    steps: [
      'Pune 80g couscous într-un bol adânc. Toarnă 100ml apă fierbinte cu sare peste el și acoperă cu o farfurie sau folie. Lasă 5 minute, apoi afânează cu o furculiță.',
      'Deconghelează 150g legume congelate sub apă caldă sau direct în tigaie.',
      'Încălzește 5ml ulei într-o tigaie la foc mediu. Adaugă legumele și gătește 5-6 minute amestecând ocazional până sunt calde și ușor rumenite.',
      'Usucă fileul de pește bine cu prosop de hârtie. Condimentează cu sare și piper.',
      'Într-o altă tigaie, încălzește restul de 5ml ulei la foc mediu-mare. Gătește peștele 3-4 minute pe fiecare parte.',
      'Aranjează couscous-ul pe farfurie, legumele alături și fileul de pește deasupra.',
      'Condimente opționale: lămâie, usturoi, boia dulce, pătrunjel — nu influențează caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'dinner_7',
    name: 'Omletă cu Brânză de Vaci și Salată',
    type: 'dinner',
    fixed: false,
    budgetTier: 'budget',
    baseCost: 28,
    baseCalories: 529,
    baseMacros: { p: 36.6, c: 10.8, f: 33.3 },
    ingredients: [
      { key: 'eggs', name: 'Ouă', amount: 3, unit: 'pcs' },
      { key: 'cottage cheese', name: 'Brânză de vaci', amount: 100, unit: 'g' },
      { key: 'tomatoes', name: 'Roșii', amount: 100, unit: 'g' },
      { key: 'cucumbers', name: 'Castraveți', amount: 100, unit: 'g' },
      { key: 'sunflower oil', name: 'Ulei de floarea soarelui', amount: 5, unit: 'ml' },
    ],
    steps: [
      'Bate cele 3 ouă cu un praf de sare și piper.',
      'Încălzește 5ml ulei într-o tigaie la foc mediu-mic. Toarnă ouăle și lasă marginile să se întărească fără să amesteci, aproximativ 2 minute.',
      'Pune 100g brânză de vaci în centrul omletei și pliază în două. Lasă pe foc încă 1-2 minute până brânza se încălzește ușor.',
      'Taie 100g roșii în felii și 100g castraveți în rondele.',
      'Servește omleta cu salata de roșii și castraveți alături.',
      'Condimente opționale: sare, piper, ulei de măsline stropit pe salată, ceapă verde — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

{
  id: 'dinner_8',
  name: 'Piept de Pui cu Mozzarella la Cuptor',
  type: 'dinner',
  fixed: false,
  budgetTier: 'medium',
  baseCost: 45,
  baseCalories: 520,
  baseMacros: { p: 58.4, c: 4.2, f: 28.8 },
  ingredients: [
    { key: 'chicken breast', name: 'Piept de pui', amount: 250, unit: 'g' },
    { key: 'mozzarella', name: 'Mozzarella', amount: 80, unit: 'g' },
    { key: 'tomatoes', name: 'Roșii', amount: 100, unit: 'g' },
    { key: 'olive oil', name: 'Ulei de măsline', amount: 10, unit: 'ml' },
  ],
  steps: [
    'Preîncălzește cuptorul la 200°C.',
    'Pune 250g piept de pui într-o tavă unsă cu 10ml ulei de măsline. Condimentează cu sare, piper și oregano pe ambele părți.',
    'Taie 100g roșii în felii rotunde și aranjează deasupra pieptului de pui.',
    'Taie 80g mozzarella în felii și pune deasupra roșiilor.',
    'Bagă tava în cuptor și coace 25-30 minute până pieptul de pui este gătit complet și mozzarella este topită și ușor aurie.',
    'Lasă să se odihnească 3-4 minute înainte de a servi.',
  ],
},

{
  id: 'dinner_9',
  name: 'Pui la Tigaie cu Unt și Usturoi',
  type: 'dinner',
  fixed: false,
  budgetTier: 'medium',
  baseCost: 42,
  baseCalories: 520,
  baseMacros: { p: 52.6, c: 3.2, f: 28.4 },
  ingredients: [
    { key: 'chicken breast', name: 'Piept de pui', amount: 280, unit: 'g' },
    { key: 'butter', name: 'Unt', amount: 25, unit: 'g' },
    { key: 'garlic', name: 'Usturoi', amount: 15, unit: 'g' },
    { key: 'lemon', name: 'Lămâie', amount: 30, unit: 'g' },
  ],
  steps: [
    'Taie 280g piept de pui în fâșii sau lasă-l întreg. Condimentează cu sare, piper și paprika pe ambele părți.',
    'Încălzește tigaia la foc mediu-mare. Adaugă 25g unt și lasă-l să se topească și să facă spumă.',
    'Adaugă puiul și gătește 4-5 minute pe o parte fără să miști, până devine auriu.',
    'Întoarce puiul și adaugă 15g usturoi tocat mărunt. Gătește încă 4-5 minute, stropind puiul cu untul și usturoiul din tigaie.',
    'Verifică că puiul este gătit complet — sucul trebuie să fie limpede când înțepi cu un cuțit.',
    'Stoarce puțin suc de lămâie deasupra înainte de servire pentru prospețime. Servește imediat.',
  ],
},

{
  id: 'dinner_10',
  name: 'Supă Cremă de Legume cu Frișcă',
  type: 'dinner',
  fixed: false,
  budgetTier: 'budget',
  baseCost: 24,
  baseCalories: 380,
  baseMacros: { p: 8.2, c: 42.6, f: 18.4 },
  ingredients: [
    { key: 'potatoes', name: 'Cartofi', amount: 200, unit: 'g' },
    { key: 'carrots', name: 'Morcovi', amount: 100, unit: 'g' },
    { key: 'onions', name: 'Ceapă', amount: 80, unit: 'g' },
    { key: 'garlic', name: 'Usturoi', amount: 10, unit: 'g' },
    { key: 'heavy cream', name: 'Frișcă', amount: 80, unit: 'ml' },
    { key: 'butter', name: 'Unt', amount: 15, unit: 'g' },
  ],
  steps: [
    'Curăță și taie 200g cartofi, 100g morcovi și 80g ceapă în cuburi mari.',
    'Topește 15g unt într-o oală la foc mediu. Adaugă ceapa și călește 3-4 minute până devine translucidă.',
    'Adaugă 10g usturoi tocat, morcovii și cartofii. Amestecă 1-2 minute.',
    'Toarnă 600ml apă sau supă de legume și fierbe 20-25 minute până legumele sunt moi.',
    'Pasează cu un blender vertical până obții o cremă fină. Dacă e prea groasă adaugă puțină apă.',
    'Adaugă 80ml frișcă și amestecă bine. Condimentează cu sare și piper după gust. Servește cu crutoane opțional.',
  ],
},

  // ============ GUSTĂRI ============

  {
    id: 'snack_1',
    name: 'Băutură Proteică K-Classic',
    type: 'snack',
    fixed: true,
    budgetTier: 'budget',
    baseCost: 27,
    baseCalories: 217,
    baseMacros: { p: 35, c: 16.5, f: 0.9 },
    ingredients: [
      { key: 'protein drink', name: 'Băutură proteică K-Classic', amount: 350, unit: 'g' },
    ],
    steps: [
      'Agită bine sticla înainte de deschidere.',
      'Servește rece, direct din frigider sau după răcire cu gheață.',
      'Ideală imediat după antrenament, în primele 30 de minute pentru recuperare optimă.',
    ],
  },

  {
    id: 'snack_2',
    name: 'Brânzică Dulce cu Banană',
    type: 'snack',
    fixed: true,
    budgetTier: 'budget',
    baseCost: 17,
    baseCalories: 236,
    baseMacros: { p: 18.5, c: 41, f: 0.25 },
    ingredients: [
      { key: 'sweet cheese', name: 'Brânzică dulce BigLapik', amount: 100, unit: 'g' },
      { key: 'bananas', name: 'Banane', amount: 80, unit: 'g' },
    ],
    steps: [
      'Scoate brânzica din frigider cu 5 minute înainte pentru o textură mai cremoasă.',
      'Curăță banana și taie-o în felii subțiri.',
      'Mănâncă brânzica direct din pachet, cu bananele alături sau amestecate înăuntru.',
      'Nu necesită preparare — perfectă ca gustare rapidă după antrenament sau între mese.',
    ],
  },

  {
    id: 'snack_3',
    name: 'Iaurt Grecesc cu Banană',
    type: 'snack',
    fixed: true,
    budgetTier: 'budget',
    baseCost: 19,
    baseCalories: 187,
    baseMacros: { p: 13.1, c: 28.7, f: 3.3 },
    ingredients: [
      { key: 'greek yogurt', name: 'Iaurt grecesc 2%', amount: 150, unit: 'g' },
      { key: 'bananas', name: 'Banane', amount: 100, unit: 'g' },
    ],
    steps: [
      'Scoate iaurtul din frigider, toarnă-l într-un bol mic.',
      'Curăță banana și taie-o în felii subțiri deasupra iaurtului.',
      'Mănâncă imediat — perfectă ca gustare rapidă între mese sau înainte de antrenament.',
      'Condimente opționale: scorțișoară sau un strop de miere — nu influențează semnificativ caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'snack_4',
    name: 'Chefir cu Ovăz',
    type: 'snack',
    fixed: true,
    budgetTier: 'budget',
    baseCost: 12,
    baseCalories: 269,
    baseMacros: { p: 13.1, c: 31.1, f: 9.05 },
    ingredients: [
      { key: 'kefir', name: 'Chefir 2.5%', amount: 250, unit: 'g' },
      { key: 'oats', name: 'Fulgi de ovăz', amount: 40, unit: 'g' },
    ],
    steps: [
      'Toarnă 250g chefir într-un pahar sau bol.',
      'Adaugă 40g fulgi de ovăz și amestecă bine.',
      'Poți consuma imediat pentru o textură mai lichidă sau lasă 10 minute pentru ca ovăzul să absoarbă chefirul și să devină mai cremos.',
      'Perfectă ca gustare rapidă sau înainte de culcare pentru proteine cu absorbție lentă.',
      'Condimente opționale: scorțișoară — nu influențează caloriile și nu sunt obligatorii.',
    ],
  },

  {
    id: 'snack_5',
    name: 'Ouă Fierte',
    type: 'snack',
    fixed: true,
    budgetTier: 'budget',
    baseCost: 9,
    baseCalories: 228,
    baseMacros: { p: 12, c: 1.2, f: 16 },
    ingredients: [
      { key: 'eggs', name: 'Ouă', amount: 2, unit: 'pcs' },
    ],
    steps: [
      'Pune apă la fiert. Adaugă cele 2 ouă cu o lingură pentru a nu le crăpa.',
      'Fierbe exact 10 minute pentru ouă tari sau 7 minute pentru gălbenuș cremos.',
      'Pune ouăle în apă rece 3-4 minute, curăță coaja și mănâncă.',
      'Cea mai simplă și mai ieftină gustare bogată în proteine — ideală oricând în zi.',
      'Condimente opționale: sare, piper, muștar — nu influențează caloriile și nu sunt obligatorii.',
    ],
  },

]

export const getRecipesByType = (type) => recipes.filter(r => r.type === type)
export const getRecipeById = (id) => recipes.find(r => r.id === id)
export const getRecipesByBudget = (maxCostPerMeal) => recipes.filter(r => r.baseCost <= maxCostPerMeal)