import { moldovanProducts, getAveragePriceForIngredient } from './moldovanProducts'

const ingredientNamesRo = {
  'chicken breast': 'Piept de pui', 
  'mozzarella': 'Mozzarella',
'cream cheese': 'Cremă de brânză',
'parmesan': 'Parmezan',
'feta': 'Brânză feta',
  'cottage cheese': 'Brânză de vaci 4-5%',
  'cottage cheese 9': 'Brânză de vaci 9%',
  'chicken thighs': 'Pulpe de pui',
  'minced meat': 'Carne tocată',
  'ham': 'Șuncă',
  'cottage cheese 0': 'Brânză de vaci 0%',
  'lemon': 'Lămâie',
  'butter': 'Unt',
  'chicken sausages': 'Mici de pui',
  'tuna': 'Ton',
  'fish fillet': 'File de pește',
  'sea bream': 'Doradă',
  'chicken meatballs': 'Perișoare de pui',
  'eggs': 'Ouă',
  'sugar': 'Zahăr',
  'greek yogurt': 'Iaurt grecesc',
  'kefir': 'Chefir',
  'milk': 'Lapte',
  'sour cream': 'Smântână',
  'sweet cheese': 'Brânzică dulce',
  'protein drink': 'Băutură proteică',
  'oats': 'Fulgi de ovăz',
  'rice': 'Orez',
  'buckwheat': 'Hrișcă',
  'pasta': 'Paste făinoase',
  'bread': 'Pâine',
  'breadcrumbs': 'Pesmeți măcinați',
  'cornmeal': 'Mălai',
  'flour': 'Făină',
  'couscous': 'Couscous',
  'lentils': 'Linte roșie',
  'chickpeas': 'Năut',
  'dried beans': 'Fasole uscată',
  'potatoes': 'Cartofi',
  'sweet potato': 'Cartof batат',
  'cabbage': 'Varză',
  'carrots': 'Morcovi',
  'tomatoes': 'Roșii',
  'cucumbers': 'Castraveți',
  'bell peppers': 'Ardei gras',
  'onions': 'Ceapă',
  'garlic': 'Usturoi',
  'broccoli': 'Broccoli',
  'mushrooms': 'Ciuperci',
  'avocado': 'Avocado',
  'frozen spinach': 'Spanac congelat',
  'frozen broccoli': 'Broccoli congelat',
  'frozen peas': 'Mazăre congelată',
  'frozen vegetables mix': 'Legume congelate mix',
  'apples': 'Mere',
  'bananas': 'Banane',
  'pears': 'Pere',
  'oranges': 'Portocale',
  'canned beans': 'Fasole la conservă',
  'canned corn': 'Porumb la conservă',
  'canned peas': 'Mazăre la conservă',
  'condensed milk': 'Lapte condensat',
  'bors': 'Borș acru',
  'leustean': 'Leuștean',
  'heavy cream': 'Frișcă',
  'pasta sauce': 'Sos de paste',
  'sunflower oil': 'Ulei de floarea soarelui',
  'olive oil': 'Ulei de măsline',
  'zucchini': 'Dovlecei',
  'beetroot': 'Sfeclă roșie',
  'eggplant': 'Vinete',
  'kiwi': 'Kiwi',
  'cauliflower': 'Conopidă',
  'strawberries': 'Căpșuni',
  'blueberries': 'Afine',
  'ginger': 'Ghimbir',
  'iceberg lettuce': 'Salată iceberg',
  'rucola': 'Rucola',
  'fresh spinach': 'Spanac proaspăt',
  'sauerkraut': 'Varză murată',
  'dill': 'Mărar',
  'parsley': 'Pătrunjel',
  'cashews': 'Nuci de caju',
  'vinegar': 'Oțet de masă',
  'balsamic vinegar': 'Oțet balsamic',
  'sesame oil': 'Ulei de susan',
  'peanuts': 'Arahide',
  'bulgur': 'Bulgur',
  'almonds': 'Migdale',
  'raisins': 'Stafide',
  'dates': 'Curmale',
  'yeast': 'Drojdie uscată',
  'baking soda': 'Bicarbonat de sodiu',
  'corn starch': 'Amidon din porumb',
  'baking powder': 'Praf de copt',
  'vanilla sugar': 'Zahăr vanilinat',
  'vanilla extract': 'Esență de vanilie',
  'canned tomatoes': 'Roșii decojite la conservă',
  'crushed tomatoes': 'Roșii pasate',
  'tomato paste': 'Pastă de tomate',
  'black beans': 'Fasole neagră',
  'cooked lentils': 'Linte gătită',
  'cocoa': 'Cacao pudră',
  'gelatin': 'Gelatină',
  'powdered sugar': 'Zahăr pudră',
  'jelly': 'Jeleu (orice gust)',
  'black olives': 'Măsline negre',
  'honey': 'Miere',
  'green olives': 'Măsline verzi',
  'potato starch': 'Amidon de cartofi',
  'tomato paste': 'Pastă de tomate',
  'pesto': 'Sos pesto',
  'mustard': 'Muștar',
  'soy sauce': 'Sos de soia',
  'adjika': 'Adjică',
  'salmon': 'Somon',
  'lavash': 'Lavaș',
  'shrimp': 'Creveți',
  'sweet chili sauce': 'Sos chilli dulce',
  'protein powder': 'Proteină din zer',
  'satsebeli': 'Sos Satsebeli/Mexicano',
  'chicken wings': 'Aripi de pui',
  'minced beef': 'Carne tocată de vită',
  'turkey breast': 'Piept de curcan',
  'filo pastry': 'Foi de plăcinte',
  'marinated chicken': 'Gambe de pui marinate',
}

const ingredientCategories = {
  'chicken breast': 'Meat and fish',
  'vinegar': 'Other',
  'protein powder': 'Other',
  'canned tomatoes': 'Canned foods',
  'tomato paste': 'Canned foods',
  'lavash': 'Grains and bread',
  'filo pastry': 'Grains and bread',
  'pesto': 'Other',
  'mustard': 'Other',
  'salmon': 'Meat and fish',
'shrimp': 'Meat and fish',
  'soy sauce': 'Other',
  'adjika': 'Other',
  'sweet chili sauce': 'Other',
  'satsebeli': 'Other',
  'crushed tomatoes': 'Canned foods',
  'tomato paste': 'Canned foods',
  'black beans': 'Canned foods',
  'cooked lentils': 'Canned foods',
  'black olives': 'Canned foods',
  'honey': 'Other',
  'green olives': 'Canned foods',
  'balsamic vinegar': 'Other',
  'baking powder': 'Other',
  'vanilla sugar': 'Other',
  'vanilla extract': 'Other',
  'cocoa': 'Other',
  'gelatin': 'Other',
  'chicken wings': 'Meat and fish',
  'minced beef': 'Meat and fish',
  'turkey breast': 'Meat and fish',
  'marinated chicken': 'Meat and fish',
  'powdered sugar': 'Other',
  'jelly': 'Other',
  'sesame oil': 'Other',
  'chicken thighs': 'Meat and fish',
  'chicken meatballs': 'Meat and fish',
  'yeast': 'Other',
  'baking soda': 'Other',
  'corn starch': 'Other',
  'potato starch': 'Other',
  'mozzarella': 'Dairy and eggs',
  'bulgur': 'Grains and bread',
  'cream cheese': 'Dairy and eggs',
  'lemon': 'Fruits',
  'parmesan': 'Dairy and eggs',
  'feta': 'Dairy and eggs',
  'butter': 'Dairy and eggs',
  'condensed milk': 'Dairy and eggs',
  'bors': 'Other',
  'sugar': 'Other',
  'leustean': 'Other',
  'minced meat': 'Meat and fish',
  'zucchini': 'Vegetables',
  'beetroot': 'Vegetables',
  'eggplant': 'Vegetables',
  'cauliflower': 'Vegetables',
  'iceberg lettuce': 'Vegetables',
  'rucola': 'Vegetables',
  'fresh spinach': 'Vegetables',
  'sauerkraut': 'Vegetables',
  'dill': 'Vegetables',
  'parsley': 'Vegetables',
  'ginger': 'Vegetables',
  'kiwi': 'Fruits',
  'strawberries': 'Fruits',
  'blueberries': 'Fruits',
  'raisins': 'Fruits',
  'dates': 'Fruits',
  'cashews': 'Other',
  'peanuts': 'Other',
  'almonds': 'Other',
  'cottage cheese 0': 'Dairy and eggs',
  'ham': 'Meat and fish',
  'chicken sausages': 'Meat and fish',
  'heavy cream': 'Dairy and eggs',
  'tuna': 'Meat and fish',
  'tuna canned': 'Meat and fish',
  'canned tuna': 'Meat and fish',
  'fish fillet': 'Meat and fish',
  'sea bream': 'Meat and fish',
  'salmon': 'Meat and fish',
  'shrimp': 'Meat and fish',
  'eggs': 'Dairy and eggs',
  'egg': 'Dairy and eggs',
  'cottage cheese': 'Dairy and eggs',
  'cottage cheese 9': 'Dairy and eggs',
  'greek yogurt': 'Dairy and eggs',
  'greek yoghurt': 'Dairy and eggs',
  'kefir': 'Dairy and eggs',
  'milk': 'Dairy and eggs',
  'sour cream': 'Dairy and eggs',
  'sweet cheese': 'Dairy and eggs',
  'protein drink': 'Dairy and eggs',
  'oats': 'Grains and bread',
  'rice': 'Grains and bread',
  'buckwheat': 'Grains and bread',
  'pasta': 'Grains and bread',
  'bread': 'Grains and bread',
  'breadcrumbs': 'Grains and bread',
  'cornmeal': 'Grains and bread',
  'flour': 'Grains and bread',
  'couscous': 'Grains and bread',
  'lentils': 'Grains and bread',
  'chickpeas': 'Grains and bread',
  'dried beans': 'Grains and bread',
  'potatoes': 'Vegetables',
  'sweet potato': 'Vegetables',
  'cabbage': 'Vegetables',
  'carrots': 'Vegetables',
  'tomatoes': 'Vegetables',
  'tomato': 'Vegetables',
  'cucumbers': 'Vegetables',
  'cucumber': 'Vegetables',
  'bell peppers': 'Vegetables',
  'bell pepper': 'Vegetables',
  'onions': 'Vegetables',
  'onion': 'Vegetables',
  'garlic': 'Vegetables',
  'broccoli': 'Vegetables',
  'mushrooms': 'Vegetables',
  'mushroom': 'Vegetables',
  'avocado': 'Vegetables',
  'frozen spinach': 'Vegetables',
  'frozen broccoli': 'Vegetables',
  'frozen peas': 'Vegetables',
  'frozen vegetables mix': 'Vegetables',
  'spinach': 'Vegetables',
  'apples': 'Fruits',
  'apple': 'Fruits',
  'bananas': 'Fruits',
  'banana': 'Fruits',
  'pears': 'Fruits',
  'pear': 'Fruits',
  'oranges': 'Fruits',
  'orange': 'Fruits',
  'canned beans': 'Canned foods',
  'canned corn': 'Canned foods',
  'canned peas': 'Canned foods',
  'pasta sauce': 'Canned foods',
  'beans': 'Canned foods',
  'sunflower oil': 'Other',
  'olive oil': 'Other',
  'oil': 'Other',
  'vegetable oil': 'Other',
  'honey': 'Other',
  'salt': 'Other',
}

const getCategory = (foodName) => {
  const key = foodName.toLowerCase().trim()
  return ingredientCategories[key] || 'Other'
}

const getUnit = (foodName) => {
  const key = foodName.toLowerCase().trim()
  if (key === 'eggs' || key === 'egg') return 'pcs'
  if (key === 'protein powder') return 'scoops'
  if (key.includes('oil') || key.includes('milk') || key.includes('kefir')) return 'ml'
  return 'g'
}

export const generateShoppingList = (weekPlan) => {
  const totals = {}

  weekPlan.forEach(day => {
    day.meals.forEach(meal => {
      if (!meal.ingredients) return
      meal.ingredients.forEach(({ food, amount }) => {
        if (!food || food.toLowerCase() === 'water' || food.toLowerCase() === 'salt' || food.toLowerCase() === 'pepper') return
        
        const key = food.toLowerCase().trim()
        if (!totals[key]) {
          totals[key] = {
  name: ingredientNamesRo[key] || food,
  normalizedKey: key,
  amount: 0,
  category: getCategory(key),
  unit: getUnit(key),
}
        }
        totals[key].amount += amount
      })
    })
  })

  return Object.values(totals).map((item, index) => {
    const avgPrice = getAveragePriceForIngredient(item.normalizedKey)
    const estimatedPrice = avgPrice
  ? item.unit === 'scoops'
    ? Math.round(avgPrice * item.amount * 10) / 10
    : item.unit === 'pcs'
    ? Math.round(avgPrice * item.amount * 10) / 10
    : Math.round(avgPrice * item.amount / 100 * 10) / 10
  : Math.round(item.amount * 0.1)

    return {
  id: index,
  name: item.name,
  ingredientKey: item.normalizedKey,
  category: item.category,
  amount: Math.round(item.amount),
  unit: item.unit,
  estimatedPrice,
  bought: false,
}
  }).sort((a, b) => a.category.localeCompare(b.category))
}